/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: process.env.DARK_MODE ? process.env.DARK_MODE : 'class',
  content: [
    './app/**/*.{html,js,jsx,ts,tsx,mdx}',
    './components/**/*.{html,js,jsx,ts,tsx,mdx}',
    './utils/**/*.{html,js,jsx,ts,tsx,mdx}',
    './*.{html,js,jsx,ts,tsx,mdx}',
    './src/**/*.{html,js,jsx,ts,tsx,mdx}',
  ],
  presets: [require('nativewind/preset')],
  important: 'html',
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
    },
  ],
  theme: {
    extend: {
      colors: {
        background: '#fdf9f3',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f4f0ea',
        'inverse-primary': '#ffb0cc',
        'inverse-surface': '#31302d',
        'on-background': '#1c1c18',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#3e0021',
        'on-primary-fixed-variant': '#8d0051',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6a4800',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#604100',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#594048',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f8ffef',
        'on-tertiary-fixed': '#012200',
        'on-tertiary-fixed-variant': '#035300',
        outline: '#8d6f79',
        'outline-variant': '#e1bdc8',
        primary: '#b30069',
        'primary-container': '#df0e84',
        'primary-fixed': '#ffd9e4',
        'primary-fixed-dim': '#ffb0cc',
        secondary: '#7e5700',
        'secondary-container': '#feb300',
        'secondary-fixed': '#ffdeac',
        'secondary-fixed-dim': '#ffba38',
        surface: '#fdf9f3',
        'surface-bright': '#fdf9f3',
        'surface-container': '#f1ede7',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e6e2dc',
        'surface-container-low': '#f7f3ed',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dddad4',
        'surface-tint': '#b8006c',
        'surface-variant': '#e6e2dc',
        tertiary: '#046c00',
        'tertiary-container': '#068800',
        'tertiary-fixed': '#85fd6d',
        'tertiary-fixed-dim': '#69df54',
      },
      fontFamily: {
        heading: undefined,
        body: undefined,
        mono: undefined,
        headline: ['NotoSerif_400Regular', 'serif'],
        'headline-bold': ['NotoSerif_700Bold', 'serif'],
        'headline-italic': ['NotoSerif_400Regular_Italic', 'serif'],
        'headline-bold-italic': ['NotoSerif_700Bold_Italic', 'serif'],
        'body-regular': ['BeVietnamPro_400Regular', 'sans-serif'],
        'body-medium': ['BeVietnamPro_500Medium', 'sans-serif'],
        'body-bold': ['BeVietnamPro_700Bold', 'sans-serif'],
        jakarta: ['var(--font-plus-jakarta-sans)'],
        roboto: ['var(--font-roboto)'],
        code: ['var(--font-source-code-pro)'],
        inter: ['var(--font-inter)'],
        'space-mono': ['var(--font-space-mono)'],
      },
      fontWeight: {
        extrablack: '950',
      },
      fontSize: {
        '2xs': '10px',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
};
